/// <reference types="next" />
/// <reference types="next/image-types/global" />

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production' | 'test';
    readonly DEPLOYMENT_MODE: 'single-tenant' | 'multi-tenant';
    readonly DATABASE_URL: string;
    readonly REDIS_URL: string;
    readonly NEXTAUTH_SECRET: string;
    readonly NEXTAUTH_URL: string;
    readonly AI_PROVIDER: 'openai' | 'anthropic';
    readonly OPENAI_API_KEY?: string;
    readonly ANTHROPIC_API_KEY?: string;
    readonly SMTP_HOST?: string;
    readonly SMTP_PORT?: string;
    readonly SMTP_USER?: string;
    readonly SMTP_PASS?: string;
    readonly SMTP_FROM?: string;
    readonly TC_API_KEY?: string;
    readonly TC_WEBHOOK_SECRET?: string;
    readonly APP_URL: string;
    readonly LOG_LEVEL?: 'debug' | 'info' | 'warn' | 'error';
  }
}

// This file was auto-generated by `next` and should not be edited
declare global {
  namespace React {
    interface ReactElement<P = unknown, T extends string | React.JSXElementConstructor<any> = string | React.JSXElementConstructor<any>> {
      type: T;
      props: P;
      key?: React.Key | null;
    }
  }
}

export {};
