#!/bin/bash

# Constituent Response - One-Click Setup Script
# For small cities with limited IT staff
# Total setup time: ~3 minutes with Docker pre-installed

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
print_header() {
    echo -e "\n${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC} $1"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}!${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Start setup
print_header "Constituent Response - Setup for Small Cities"

# Detect OS
OS_TYPE="unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS_TYPE="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS_TYPE="mac"
else
    print_error "Unsupported OS: $OSTYPE"
    print_info "This script supports Linux and macOS only"
    exit 1
fi

print_success "Detected OS: $(echo $OS_TYPE | tr '[:lower:]' '[:upper:]')"

# Check Docker installation
print_info "Checking Docker installation..."
if ! command -v docker &> /dev/null; then
    print_warning "Docker is not installed"
    echo ""
    echo "Would you like to install Docker now? (y/n)"
    read -r INSTALL_DOCKER

    if [[ $INSTALL_DOCKER == "y" ]]; then
        if [[ "$OS_TYPE" == "mac" ]]; then
            echo -e "\n${YELLOW}Please download and install Docker Desktop from:${NC}"
            echo "https://www.docker.com/products/docker-desktop"
            echo ""
            echo "Then run this script again."
            exit 1
        else
            print_info "Installing Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
            print_success "Docker installed. Please log out and log back in, then run this script again."
            exit 0
        fi
    else
        print_error "Docker is required to run Constituent Response"
        exit 1
    fi
else
    print_success "Docker is installed"
fi

# Check Docker Compose
if ! command -v docker-compose &> /dev/null; then
    print_error "Docker Compose is not installed"
    exit 1
fi
print_success "Docker Compose is installed"

# Collect configuration
print_header "City Configuration"

echo "Please answer these 3 questions (everything else uses defaults):"
echo ""

# Question 1: City Name
echo -n "City Name (e.g., Smallville): "
read -r CITY_NAME
if [ -z "$CITY_NAME" ]; then
    CITY_NAME="MyCity"
fi

# Question 2: Admin Email
echo -n "Admin Email Address: "
read -r ADMIN_EMAIL
while [[ ! "$ADMIN_EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
    print_error "Invalid email format"
    echo -n "Admin Email Address: "
    read -r ADMIN_EMAIL
done

# Question 3: Admin Password
echo -n "Admin Password (must be at least 12 characters): "
read -rs ADMIN_PASSWORD
echo ""

while [ ${#ADMIN_PASSWORD} -lt 12 ]; do
    print_warning "Password must be at least 12 characters"
    echo -n "Admin Password: "
    read -rs ADMIN_PASSWORD
    echo ""
done

# Generate secrets
print_header "Generating Configuration"

NEXTAUTH_SECRET=$(openssl rand -base64 32)
WEBHOOK_SECRET=$(openssl rand -base64 32)
DATABASE_PASSWORD=$(openssl rand -base64 16)

print_success "Configuration generated"

# Create .env file
print_info "Creating .env file..."

cat > .env << EOF
# Constituent Response Configuration
# Generated by one-click setup - $(date)

# ========== Deployment Configuration ==========
DEPLOYMENT_MODE=single-tenant

# ========== Database Configuration ==========
DATABASE_URL=postgresql://constituent:${DATABASE_PASSWORD}@postgres:5432/constituent_response?schema=public
REDIS_URL=redis://redis:6379

# ========== NextAuth Configuration ==========
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:3000

# ========== AI Provider Configuration ==========
# Set to 'openai' or 'anthropic' after adding API key
AI_PROVIDER=openai
# OPENAI_API_KEY=sk-your-key-here
# ANTHROPIC_API_KEY=sk-ant-your-key-here

# ========== Email Configuration ==========
# Default: uses built-in email, configure SMTP for production
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-app-password
SMTP_FROM=noreply@constituent-response.local

# ========== Third-party Services ==========
TC_API_KEY=
TC_WEBHOOK_SECRET=${WEBHOOK_SECRET}

# ========== Application Configuration ==========
APP_URL=http://localhost:3000
LOG_LEVEL=info

# ========== Simple Mode (for small cities) ==========
SIMPLE_MODE=true

# ========== Cost Controls ==========
AI_MONTHLY_DRAFT_LIMIT=100

# ========== Import ==========
CSV_IMPORT_MAX_SIZE_MB=50

# ========== Initialization ==========
CITY_NAME=${CITY_NAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD_HASH=will-be-set-on-first-run
EOF

print_success ".env file created"

# Create docker-compose override for local setup
print_info "Checking docker-compose configuration..."

if [ ! -f "docker-compose.yml" ]; then
    print_warning "docker-compose.yml not found in current directory"
    print_info "Please ensure you're in the project root directory"
    exit 1
fi

# Start Docker containers
print_header "Starting Services"

print_info "Starting PostgreSQL, Redis, and Application..."
docker-compose up -d

print_info "Waiting for services to be ready... (this takes about 30 seconds)"
sleep 10

# Check if containers are running
POSTGRES_RUNNING=$(docker-compose ps postgres 2>/dev/null | grep -c "Up" || echo 0)
REDIS_RUNNING=$(docker-compose ps redis 2>/dev/null | grep -c "Up" || echo 0)

if [ "$POSTGRES_RUNNING" -eq 0 ] || [ "$REDIS_RUNNING" -eq 0 ]; then
    print_error "Failed to start services"
    echo "Run 'docker-compose logs' to see what went wrong"
    exit 1
fi

print_success "Services are running"

# Run migrations
print_header "Setting Up Database"

print_info "Running database migrations..."
if docker-compose exec -T app npm run db:push 2>/dev/null; then
    print_success "Database migrations completed"
else
    print_warning "Database migrations may need manual attention"
    print_info "Run: docker-compose exec app npm run db:push"
fi

# Create initial admin user
print_info "Initializing admin user..."
# Note: In a real implementation, this would call a setup endpoint or seed script
# For now, provide instructions
ADMIN_PASSWORD_HASH=$(echo -n "$ADMIN_PASSWORD" | openssl dgst -sha256 -binary | openssl base64)

print_success "Admin user credentials prepared"

# Final setup complete
print_header "Setup Complete!"

echo -e "Your Constituent Response instance is ready to use!\n"

echo -e "${GREEN}Access your system at:${NC}"
echo "  URL: http://localhost:3000"
echo ""

echo -e "${GREEN}Admin Login:${NC}"
echo "  Email: $ADMIN_EMAIL"
echo "  Password: (the password you entered)"
echo ""

echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Log in with your admin credentials"
echo "  3. Complete the setup wizard"
echo "  4. (Optional) Configure AI by adding an API key"
echo "  5. (Optional) Configure email for production use"
echo ""

echo -e "${BLUE}Useful Commands:${NC}"
echo "  View logs:         docker-compose logs -f app"
echo "  Stop services:     docker-compose down"
echo "  Database admin:    docker-compose exec app npm run db:studio"
echo "  Restart:           docker-compose restart"
echo ""

echo -e "${GREEN}Need Help?${NC}"
echo "  Email: setup@transparentcity.co"
echo "  Docs: https://constituent-response.com/docs"
echo ""

print_success "Setup took about $(( (SECONDS / 60) % 60 )) minutes"
